specVersion: 0.0.5
schema:
  file: ./schema.graphql
dataSources:
  {{#vault}}
  - name: {{name}}
    kind: ethereum/contract
    network: {{network}}
    source:
      address: "{{address}}"
      abi: Vault
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mappings/handlers.ts
      entities:
        - YieldAggregator
        - Vault
        - VaultFee
        - Token
        - _UnderlyingToken
      abis:
        - name: Vault
          file: ./abis/Vault.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
      eventHandlers:
        - event: IncreasePosition(bytes32,address,address,address,uint256,uint256,bool,uint256,uint256)
          handler: handleIncreasePosition
  {{/vault}}
